"""initial schema

Revision ID: b7f1aff0c8f1
Revises: 
Create Date: 2026-03-04 12:47:34.469330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7f1aff0c8f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('social_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('provider_user_id', sa.Text(), nullable=False),
    sa.Column('provider_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_social_provider_user')
    )
    op.create_index('ix_social_accounts_user_id', 'social_accounts', ['user_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_workspace_group_name')
    )
    op.create_table('resource_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.Text(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('visibility', sa.Text(), server_default='workspace', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("visibility IN ('private', 'workspace')", name='ck_visibility'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_name', 'resource_type', 'resource_id', name='uq_resource_identity')
    )
    op.create_index('ix_resource_permissions_lookup', 'resource_permissions', ['service_name', 'resource_type', 'resource_id'], unique=False)
    op.create_index('ix_resource_permissions_owner', 'resource_permissions', ['owner_id'], unique=False)
    op.create_index('ix_resource_permissions_workspace', 'resource_permissions', ['workspace_id'], unique=False)
    op.create_table('workspace_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'admin', 'editor', 'viewer')", name='ck_membership_role'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_member')
    )
    op.create_index('ix_workspace_memberships_user_id', 'workspace_memberships', ['user_id'], unique=False)
    op.create_table('group_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_group_member')
    )
    op.create_index('ix_group_memberships_user_id', 'group_memberships', ['user_id'], unique=False)
    op.create_table('resource_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_permission_id', sa.UUID(), nullable=False),
    sa.Column('grantee_type', sa.Text(), nullable=False),
    sa.Column('grantee_id', sa.UUID(), nullable=False),
    sa.Column('permission', sa.Text(), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("grantee_type IN ('user', 'group')", name='ck_grantee_type'),
    sa.CheckConstraint("permission IN ('view', 'edit')", name='ck_share_permission'),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resource_permission_id'], ['resource_permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_permission_id', 'grantee_type', 'grantee_id', name='uq_resource_share')
    )
    op.create_index('ix_resource_shares_grantee', 'resource_shares', ['grantee_type', 'grantee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_resource_shares_grantee', table_name='resource_shares')
    op.drop_table('resource_shares')
    op.drop_index('ix_group_memberships_user_id', table_name='group_memberships')
    op.drop_table('group_memberships')
    op.drop_index('ix_workspace_memberships_user_id', table_name='workspace_memberships')
    op.drop_table('workspace_memberships')
    op.drop_index('ix_resource_permissions_workspace', table_name='resource_permissions')
    op.drop_index('ix_resource_permissions_owner', table_name='resource_permissions')
    op.drop_index('ix_resource_permissions_lookup', table_name='resource_permissions')
    op.drop_table('resource_permissions')
    op.drop_table('groups')
    op.drop_table('workspaces')
    op.drop_index('ix_social_accounts_user_id', table_name='social_accounts')
    op.drop_table('social_accounts')
    op.drop_table('users')
    # ### end Alembic commands ###
